### ISSUE TITLE
Doesn't install correctly under Python 3.9

### ISSUE THREAD

**Issue by thejesusofcode** [yoshi1123/mtgcard#1]
returned the following:

~$ pip3 install --no-index .
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Processing /usr/local/lib/mtgcard
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/usr/local/lib/mtgcard/setup.py", line 12, in <module>
          mtgcard.update.update_database(verbose=True)
        File "/usr/local/lib/mtgcard/mtgcard/update/__init__.py", line 77, in update_database
          with urllib.request.urlopen(req, context=cxt) as contents:
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
          return opener.open(url, data, timeout)
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
          response = meth(req, response)
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
          response = self.parent.error(
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
          return self._call_chain(*args)
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
          result = func(*args)
        File "/usr/local/Cellar/python@3.9/3.9.13/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 404: Not Found
      DOWNLOAD MTGCARD DATA BEGIN
      generating database
        CA certificate: system default CA path
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

_macOS 10.13_

**Comment by yoshi1123** [comment]
https://github.com/yoshi1123/mtgcard/commit/27624ff13eda429a4e58169c92554f1fee2d9409 should fix this. Just clone latest. Let me know if you have any problems.
